version: "3.4"
services:
  s3:
    image: minio/minio
    container_name: instagram-storage
    command: server /data
    environment:
      # ログイン時のキー
      MINIO_ACCESS_KEY: tlab-app
      MINIO_SECRET_KEY: team-lab
    volumes:
      - "./s3-data:/data"
    ports:
      - "9000:9000"
  mysql:
    image: mysql:5.7
    container_name: instagram-rdb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      # ログイン時のキー
      MYSQL_DATABASE: instagram
      MYSQL_USER: tlab-app
      MYSQL_PASSWORD: team-lab
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "./database/db-data:/var/lib/mysql"
      - "./database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: instagram-api
    volumes:
      - "./:/source"
    ports:
      - "8080:80"
